In [57]:
import numpy as np;
import timeit as timeit;

# -*- coding: utf-8 -*-
"""
Created on Sat Nov  7 13:26:09 2020

Höhere Mathematik 1, Serie 8, Gerüst für Aufgabe 2

Description: calculates the QR factorization of A so that A = QR
Input Parameters: A: array, n*n matrix
Output Parameters: Q : n*n orthogonal matrix
                   R : n*n upper right triangular matrix
Remarks: none
Example: A = np.array([[1,2,-1],[4,-2,6],[3,1,0]])
        [Q,R]=QR_Zerlegung(A)

@author: knaa
"""

def QR_Zerlegung(A):
    A = np.copy(A)                       #necessary to prevent changes in the original matrix A_in
    A = A.astype('float64')              #change to float

    n = np.shape(A)[0]

    if n != np.shape(A)[1]:
        raise Exception('Matrix is not square')

    Q = np.eye(n)
    R = A

    for j in np.arange(0,n-1):
        a = np.copy(R[j:, j]).reshape(n-j,1)
        e = np.eye(n-j)[:,0].reshape(n-j,1)
        length_a = np.linalg.norm(a)
        if a[0] >= 0: sig = +1
        else: sig = -1
        v = a + sig * length_a * e
        u = (1 / np.linalg.norm(v)) * v
        H = np.eye(n-j) - 2 * np.dot(u, u.T)
        Qi = np.eye(n)
        Qi[j:,j:] = H
        R = np.dot(Qi, R)
        Q = np.dot(Q, Qi.T)
    return(Q,R)

# Übung aus Vorlesung:
# A = np.array([[1,2,-1],[4,-2,6],[3,1,0]])
A = np.array([[1,-2,3],[-5,4,1],[2,-1,3]])
print("Start Matrix A:")
print(A)
print("--------------------------")


#b)
QR_res = QR_Zerlegung(A)
print("Matrix Q:")
print(QR_res[0])
print("Matrix R:")
print(QR_res[1])
print("--------------------------")


#c)
t1 = timeit.repeat("QR_Zerlegung(A)", "from __main__ import QR_Zerlegung, A", number=100)
t2 = timeit.repeat("np.linalg.qr(A)", "from __main__ import np, A", number=100)
avg_t1 = np.average(t1)/100
avg_t2 = np.average(t2)/100
print("t1:")
print(t1)
print("t2:")
print(t2)
print("avg_t1:")
print(avg_t1)
print("avg_t2:")
print(avg_t2)
print("--------------------------")


#d)
Test = np.random.rand(100,100)
t3 = timeit.repeat("QR_Zerlegung(Test)", "from __main__ import QR_Zerlegung, Test", number=100)
avg_t3 = np.average(t1)/100
print("t3:")
print(t3)
print("avg_t3:")
print(avg_t3)
#Unsere Erkenntnisse aus diesen Zahlen ist, dass die Funktion konstant in Belangen Performance ist.

Start Matrix A:
[[ 1 -2  3]
 [-5  4  1]
 [ 2 -1  3]]
--------------------------
Matrix Q:
[[-1.82574186e-01 -8.94427191e-01  4.08248290e-01]
 [ 9.12870929e-01 -5.79430401e-17  4.08248290e-01]
 [-3.65148372e-01  4.47213595e-01  8.16496581e-01]]
Matrix R:
[[-5.47722558e+00  4.38178046e+00 -7.30296743e-01]
 [ 2.29962732e-16  1.34164079e+00 -1.34164079e+00]
 [-2.40937142e-16  1.73797467e-17  4.08248290e+00]]
--------------------------
t1:
[0.009467000025324523, 0.009032799978740513, 0.00954300002194941, 0.01079929998377338, 0.00759180000750348]
t2:
[0.0021064000320620835, 0.00211419997503981, 0.002161199983675033, 0.002670800022315234, 0.002188499958720058]
avg_t1:
9.286780003458261e-05
avg_t2:
2.2482199943624434e-05
--------------------------
t3:
[3.1208802000037394, 2.8940020999871194, 2.6828968999907374, 2.6712828999734484, 2.719013400026597]
avg_t3:
9.286780003458261e-05
