In [3]:
import numpy as np
import scipy.linalg as la

A = np.array([[0.8,2.2,3.6], [2.0,3.0,4.0],[1.2,2.0,5.8]])
b = np.array([2.4,1.0,4.0])
(P, L, R) = la.lu(A)
print (P)
print (L)
print (R)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[1.  0.  0. ]
 [0.4 1.  0. ]
 [0.6 0.2 1. ]]
[[2. 3. 4.]
 [0. 1. 2.]
 [0. 0. 3.]]
