In [76]:
import numpy as np

x = np.array([3,-1,-4,-4,-5,-4])
y = np.array([3,-5,3,4,-2,4])
n = x.size
x_sum = sum(x)
y_sum = sum(y)

x_min_xStrich = np.zeros(n)
y_min_yStrich = np.zeros(n)
xMaly = np.zeros(n)
x_min_xStrich_quadrat = np.zeros(n)
y_min_yStrich_quadrat = np.zeros(n)
x_quadrat = pow(x, 2)
y_quadrat = pow(y, 2)
yDach = np.zeros(n)
yDach_min_yDach_strich = np.zeros(n)

x_strich = x_sum / n

y_strich = y_sum / n

for i in range(0,n):
    x_min_xStrich[i] = x[i] - x_strich
    y_min_yStrich[i] = y[i] - y_strich
    xMaly[i] = x_min_xStrich[i] * y_min_yStrich[i]
    x_min_xStrich_quadrat[i] = x_min_xStrich[i] * x_min_xStrich[i]
    y_min_yStrich_quadrat[i] = y_min_yStrich[i] * y_min_yStrich[i]

xMalySum = sum(xMaly)
x_min_xStrich_quadratSum = sum(x_min_xStrich_quadrat)
y_min_yStrich_quadratSum = sum(y_min_yStrich_quadrat)

m = xMalySum / x_min_xStrich_quadratSum
d = y_strich - m * x_strich

for i in range(0,n):
    yDach[i] = m * x[i] + d
residualvarianz = (y_min_yStrich_quadratSum/n) - (xMalySum/n)**2 / (x_min_xStrich_quadratSum/n)
#residualvarianz =

yDach_strich = sum(yDach) / n
for i in range(0,n):
    yDach_min_yDach_strich[i] = (yDach[i] - yDach_strich)**2
erklaerteVarianz = sum(yDach_min_yDach_strich) / n

totaleVarianz = residualvarianz + erklaerteVarianz

bestimmtheitsmass = erklaerteVarianz / totaleVarianz

pearson = (xMalySum/n)/(x_sum/n)*(y_sum/n)
steigungX = xMalySum / y_min_yStrich_quadratSum
achsenX = x_strich - (steigungX * y_strich)

print("x_min_xStrich:")
print(x_min_xStrich)
print("y_min_yStrich:")
print(y_min_yStrich)
print("xMaly:")
print(xMaly)
print("x_min_xStrich_quadrat:")
print(x_min_xStrich_quadrat)
print("y_min_yStrich_quadrat")
print(y_min_yStrich_quadrat)
print("x_quadrat:")
print(x_quadrat)
print("y_quadrat:")
print(y_quadrat)
print("yDach:")
print(yDach)

print("Zahlen--------------")
print("x-Strich: " + str(x_strich))
print("y-Strich: " +str(y_strich))
print("xMalySum: " +str(xMalySum))
print("x_min_xStrich_quadratSum: " + str(x_min_xStrich_quadratSum))
print("y_min_yStrich_quadratSum: " + str(y_min_yStrich_quadratSum))
print("---------Lösungen-------")
print("m: " + str(m))
print("d: " + str(d))
print("residualvarianz: " + str(residualvarianz))
print("erklaerteVarianz: " + str(erklaerteVarianz))
print("totaleVarianz: " + str(totaleVarianz))
print("bestimmtheitsmass: " + str(bestimmtheitsmass))
print("pearson: " + str(pearson))
print("pearson mit cheat: " + str(np.corrcoef(x,y)[0][1]))
print("steigungX: " + str(steigungX))
print("achsenX: " + str(achsenX))

x_min_xStrich:
[ 5.5  1.5 -1.5 -1.5 -2.5 -1.5]
y_min_yStrich:
[ 1.83333333 -6.16666667  1.83333333  2.83333333 -3.16666667  2.83333333]
xMaly:
[10.08333333 -9.25       -2.75       -4.25        7.91666667 -4.25      ]
x_min_xStrich_quadrat:
[30.25  2.25  2.25  2.25  6.25  2.25]
y_min_yStrich_quadrat
[ 3.36111111 38.02777778  3.36111111  8.02777778 10.02777778  8.02777778]
x_quadrat:
[ 9  1 16 16 25 16]
y_quadrat:
[ 9 25  9 16  4 16]
yDach:
[0.86446886 1.08424908 1.24908425 1.24908425 1.3040293  1.24908425]
Zahlen--------------
x-Strich: -2.5
y-Strich: 1.1666666666666667
xMalySum: -2.5
x_min_xStrich_quadratSum: 45.5
y_min_yStrich_quadratSum: 70.83333333333333
---------Lösungen-------
m: -0.054945054945054944
d: 1.0293040293040294
residualvarianz: 11.782661782661782
erklaerteVarianz: 0.022893772893772882
totaleVarianz: 11.805555555555555
bestimmtheitsmass: 0.0019392372333548794
pearson: 0.19444444444444448
pearson mit cheat: -0.04403677137750769
steigungX: -0.03529411764705882
achsenX: -2